# Generated by Django 5.2.6 on 2025-09-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_marca_producto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='pais',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
